### PR TITLE
(RE-9335) Enable nightly ship path alternatives

### PR DESCRIPTION
**Pull request by mwaggett**
This commit adds nonfinal paths and commands for shipping nightlies.

### CODE REVIEW

**Comment by sarameisburger** [comment]
👍

**Review by underscorgan — APPROVED** [review]
Does this need to wait for anything else before it goes in or is it good to go now?

**Comment by mwaggett** [comment]
@underscorgan I *think* it should be good to go in? This will send nonfinal builds to these new paths instead of our final ship paths on weth, if using packaging 1.0.x.
Shipping things that aren't on the 1.0.x of packaging won't barf at unrecognized entries, will it?

**Review by e-gris — COMMENTED** [review]
Reviewed without comment.

**Review by underscorgan — APPROVED** [review]

**Pull request merged**
