### PR TITLE
(PA-4781) Enable macOS 13 (ARM) for public nightlies ship

### PR DESCRIPTION
**Pull request by shubhamshinde360**

### CODE REVIEW

**Review by isaac-jha — APPROVED** [review]

**Review by joshcooper — COMMENTED** [review]
I thought `foss_platforms` in the vanagon project's repo controlled what was shipped to public nightlies, for example: https://github.com/puppetlabs/puppet-agent/blob/750d825070c8bc957cf80c360a2c70885b1dabfe/ext/build_defaults.yaml#L3-L6

So this raises a few questions for me:
* What is the real "lever" for shipping to nightlies.puppet.com?
* Do we actually need `foss_platforms` in the vanagon repo?
* How does this repo `build-data` handle a platform that is only shipped in one stream, but not another, for example, we only ship puppet-agent for RHEL6 in 7.x, but not main?

**Review by e-gris — APPROVED** [review]

**Comment by joshcooper** [comment]
@e-gris we're a little confused about what controls shipping to agent-downloads and nightlies.puppet.com. It used to be that puppet-agent's `build_defaults.yaml` needed to be updated when adding a platform. For example, we added https://github.com/puppetlabs/puppet-agent/blob/750d825070c8bc957cf80c360a2c70885b1dabfe/ext/build_defaults.yaml#L17

But AFAICT, we no longer need to update `foss_platforms` in puppet-agent?

I say that because macOS 13 ARM packages started shipping to agent-downloads before @shubhamshinde360 change above. For example, this package was shipped July 21:

http://agent-downloads.delivery.puppetlabs.net/puppet-agent/8.1.0.58/repos/apple/13/puppet8/arm64/

I think it's because in CJC we execute https://github.com/puppetlabs/ci-job-configs/blob/5de9b96485eb6be54e43880e2d49a7a0d10e2a04/resources/scripts/puppet-agent-internal-promotion.sh#L175

Note we only specify 2 arguments. So the third argument `foss_only` is falsey: https://github.com/puppetlabs/packaging/blob/affecba5dfacc5862fc7199895ccf11b69153570/tasks/nightly_repos.rake#L144

So then we skip this entire block and just include everything: https://github.com/puppetlabs/packaging/blob/affecba5dfacc5862fc7199895ccf11b69153570/tasks/nightly_repos.rake#L149

So everything that was built and shipped to builds.d.pl.net in our pipeline is rsynced to agent-downloads. But in order to ship builds to our external https://nightlies.puppet.com, we have to update this repo.

So then is there any reason to keep `foss_platforms` in puppet-agent?

**Comment by e-gris** [comment]
I have some time today I think and I'll produce a definitive answer. 

My (possibly faulty) recollection is that packaging has a contrary-to-expectations order of resolving these settings where local settings are overridden by environment variables which are overridden by build-data.

**Comment by e-gris** [comment]
I was almost correct.

Local settings (build_defaults.yaml) are loaded first.

Then build-data is cloned and loaded (https://github.com/puppetlabs/packaging/blob/affecba5dfacc5862fc7199895ccf11b69153570/tasks/fetch.rake#L40); first the 'team_data_branch' then the 'project_data_branch'

Each step clobbers any previous conflicting setting but leaves non-conflicts intact.

Here's the part where local data is intentionally clobbered: https://github.com/puppetlabs/packaging/blob/affecba5dfacc5862fc7199895ccf11b69153570/tasks/load_extras.rake#L10

There is no option to _not_ use build-data. So, local settings are almost useless _except_ when build-data doesn't define an override.

To answer your question directly: I see no reason to keep `foss_platforms` in puppet agent.

To answer your question with a broader opinion: I think it is bad practice for `packaging` to override/change/ignore anything that is in the source code. I feel the `build-data` repository shouldn't exist. Defaults should be part of packaging itself but local settings should have highest precedence.

**Comment by joshcooper** [comment]
Thanks @e-gris If it's ok, I'd like to merge this to unblock shipping to public nightlies and we can figure out if `foss_platform` updates are still needed in `puppet-agent` separately

**Pull request merged**
