### PR TITLE
(maint) Update Apple macOS signing server

### PR DESCRIPTION
**Pull request by mhashizume**

### CODE REVIEW

**Review by e-gris — COMMENTED** [review]
IIRC, we cannot mix OS/X signing servers. 

Moving to app-2 makes sense to me but there may be transition issues when doing so.  This could 'just work' but I fear that there may be a risk that we'll need to get more clever about it to keep things from getting mixed up.

**Comment by mhashizume** [comment]
@e-gris What do you mean wrt mixing servers? If you mean making sure that dependent projects also change the signing server, I have a corresponding PR up in puppet-agent: https://github.com/puppetlabs/puppet-agent/pull/2246

Would this PR and the above linked PR need to be merged in a particular sequence for everything to work?

Thanks!

**Comment by joshcooper** [comment]
Is there a way to point your puppet-agent PR to this branch of build-data (like we do for VANAGON_LOCATION) and verify the signing works. Then merge both PRs simultaneously (after the 7.17.0 release)?

**Comment by e-gris** [comment]
@mhashizume Somewhat like that but a little bit more nebulous. When we were doing this before and switched over to prod-2, some things went fubar because some-something-previously signed with the old server-something-something.

I just wanted to communicate that because of the number of WTF? moments we were having when trying to get the new stuff set up. (And I'm definitely writing from the peanut-gallery here, I wasn't directly involved but had to do one urgent rollback)

**Comment by mhashizume** [comment]
Gotcha @e-gris . I'll take @joshcooper 's advice and wait til after the release to avoid any unpleasant surprises. In the meantime, I'll see if I can manually test with this branch.

**Pull request merged**
