### PR TITLE
Add "no-tty" to rpm metadata signing

### PR DESCRIPTION
**Pull request by shrug**

### CODE REVIEW

**Comment by ghost** [comment]
Are things being written/printed somewhere... or is this precautionary only?

**Comment by mwaggett** [comment]
@jennaesq The command was failing when we were trying to ship via pipeline: http://jenkins-compose.delivery.puppetlabs.net/job/PDK_Test_Autoship/43/console

This was our best attempt at a solution for the moment.. 😅

**Review by mwaggett — APPROVED** [review]

**Review by ghost — APPROVED** [review]
I don't know the reasoning behind the change... but, think it's a great option to use... especially with any automation. 

Thanks @mwaggett!  You must have been replying while I was typing.

**Comment by shrug** [comment]
We use https://github.com/puppetlabs/build-data/blob/release/builder_data.yaml#L52 for apt, but we don't have the option of passing other gpg flags (I don't think?) to that bit

**Pull request merged**
