### PR TITLE
(maint) Add signing server for osx

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
@heathseals are any of those things sensitive data that we con't want to make publicly available? For sure SIGNING_KEYCHAIN_PW we shouldn't. Also, with SIGNING_KEYCHAIN, will that work for different users? LIke, when I need to sign foss packages for release vs. jenkins promoting into PE?

**Comment by melissa** [comment]
Also, I'm worried that we don't always have those env vars loaded and available for use. How are we doing that for PE?

**Comment by heathseals** [comment]
@melissa for PE it uses a mix of constants in enterprise-dist and env vars sourced by the jenkins user on the signer.  imo the only sensitive data is the keychain pw and that should continue to be sourced from the environment of the user doing the signing.

**Comment by heathseals** [comment]
additionally, all of the vars within packaging are prefaced by OSX_.  we should probably fix up enterprise-dist to match so we don't have multiple vars for the same data.

**Comment by stahnma** [comment]
Let's ticket that second comment @heathseals

**Comment by melissa** [comment]
We still need to figure out how to make these setting available to jenkins for promotion. Does anyone know if jenkins has TEAM set to release? Should these settings be added to the puppet-agent project?

**Comment by heathseals** [comment]
advantage/disadvantages of having jenkins set TEAM to release ( which it currently doesn't ) vs having these in the build-data for the individual project?  i'm not certain of the answer to this.

**Comment by heathseals** [comment]
otherwise, i'm :+1: on this.

**Comment by melissa** [comment]
I'm closing this in favor of keeping this data in the puppet-agent repo. I think that course of action makes more sense for us at this moment in time. https://github.com/puppetlabs/puppet-agent/pull/220

**Pull request closed without merging**
