### PR TITLE
(maint) Add signing_server to build-data

### PR DESCRIPTION
**Pull request by mwaggett**

### CODE REVIEW

**Review by shrug — APPROVED** [review]

**Comment by underscorgan** [comment]
maybe want to merge this monday morning in case it breaks anything we're not anticipating?

**Comment by mwaggett** [comment]
¯\_(ツ)_/¯ I'm fine waiting if you'd feel better about that.

**Comment by underscorgan** [comment]
it's after 4 on a Friday and I don't have a solid picture of what pipelines changing this might affect, so I'd rather not merge it unless we're going to have some time to catch things that might explode

**Comment by mwaggett** [comment]
yeah, I get that, and that is totally fine with me.
I just can't imagine this breaking anything - anything that uses `signing_server` would have to have it defined elsewhere, and the elsewhere would override this, right?

**Comment by shrug** [comment]
The only thing *might* be the internal agent/ agent S3 ship pipelines. They should be ok with this change but let's merge Monday

**Pull request merged**
