### PR TITLE
(RE-13178)(RE-13181)(RE-13184)(RE-13187) Remove eol platforms

### PR DESCRIPTION
**Pull request by sarameisburger**
Removes:
  - cumulus-2.2-amd64
  - debian-7-amd64
  - debian-7-i386
  - eos-4-i386
  - fedora-f25-i386
  - fedora-f25-x86_64
  - fedora-f26-x86_64
  - fedora-25-i386
  - fedora-25-x86_64
  - fedora-26-x86_64
  - fedora-27-x86_64
  - fedora-28-x86_64
  - fedora-29-x86_64
  - osx-10.10-x86_64
  - osx-10.11-x86_64
  - osx-10.12-x86_64
  - osx-10.13-x86_64
  - sles-11-i386
  - sles-11-x86_64
  - ubuntu-14.04-amd64
  - ubuntu-14.04-i386

### CODE REVIEW

**Comment by sarameisburger** [comment]
Any that shouldn't be removed or others that I can remove?

**Review by underscorgan — APPROVED** [review]
This looks like the right list to me

**Review by e-gris — APPROVED** [review]
I had thought el-5 had reached EOL but that's not until November.

**Comment by ciprianbadescu** [comment]
sles-11/ubuntu-14.04 are still supported by puppet-agent

**Comment by sarameisburger** [comment]
PR to add back platforms: https://github.com/puppetlabs/build-data/pull/168

**Pull request merged**
