### PR TITLE
Add default mocks and cows to team builder_data

### PR DESCRIPTION
**Pull request by shrug**
Adding these here will override entries in the project metadata and allow us to set up a set of default PE build platforms. These can be overridden in the project-specific branches.

### CODE REVIEW

**Comment by clantant** [comment]
:+1:

**Comment by melissa** [comment]
As is, wont this override all the FOSS cows/mocks as well?

**Comment by haus** [comment]
indeed.

**Comment by melissa** [comment]
yeah, so I'm :-1:  on this

**Comment by shrug** [comment]
What is the correct answer? Add the proper entries to the foss project branches? Ot drop this and add the pe mocks to the pe project branches?

**Comment by melissa** [comment]
I think ideally we could namespace the cows and mocks (i.e.  `pl-cows` and `pe-cows`), but that would also require updates to the automation in the packaging repo, or something. Of course, that's not the only answer here. We could also create another pe- specific file that gets pulled down for all pe projects, that gets loaded after team data, but before project data.

**Comment by haus** [comment]
Namespacing the cows and mocks sounds messy. If we went down that road, we shouldn't do pl-cows, but rather have settings under pe and under foss. Model it in the structure and not it the name.

**Comment by shrug** [comment]
Something like this? Assuming the logic in packaging to handle it...

**Comment by haus** [comment]
@shrug yea, that was what i was imagining. when we did it we would probably want to lose final_mocks and just move to mocks, as the final bit is legacy.

**Comment by melissa** [comment]
I'm on board with that

**Comment by shrug** [comment]
closing to retarget at pe-release, because hey look we have a pe-release branch

**Pull request closed without merging**
